In [13]:
!pip install --user networkx
!pip install --upgrade ipykernel

You should consider upgrading via the 'pip install --upgrade pip' command.
     |████████████████████████████████| 122kB 2.1MB/s eta 0:00:01
  Found existing installation: ipykernel 5.1.2
    Uninstalling ipykernel-5.1.2:
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/__pycache__/ipykernel_launcher.cpython-35.pyc'
Consider using the `--user` option or check the permissions.

You should consider upgrading via the 'pip install --upgrade pip' command.


In [10]:
import numpy as np
import random
from matplotlib import pyplot as plt
from matplotlib.colors import ListedColormap, LinearSegmentedColormap
import networkx as ntx

from datetime import date

In [5]:
def calculateNeighbours(location, t_size):
    # We first calculate all 9 cells in the neighbourhood,
    # and then filter out itself and the ones in the cross
    # by filtering elements with manhattan distance not equal to one.
    return list(filter(lambda x: abs(location[0]-x[0])+abs(location[1]-x[1])==1, [(x,y) for x in range(location[0]-1 if location[0]-1 > -1 else 0, location[0]+2 if location[0]+1<t_size else t_size) for y in range(location[1]-1 if location[1]-1 > -1 else 0, location[1]+2 if location[1]+1<t_size else t_size)]))

In [6]:
def generateGrid(t_size):
    # Initially all cells are set as not visited
    # 1 marks blocked, 0 marks unblocked, -1 for not visited
    grid = np.full(shape = (t_size, t_size), fill_value = -1, dtype = np.int8)

    # A random location on the grid to begin with, and mark it visited
    begin = (random.randint(0, t_size - 1), random.randint(0, t_size-1))
    grid[begin[0], begin[1]] = 1

    # Using a stack as a frontier, so we can use DFS to generate the blocked paths
    frontier = []
    frontier.append(begin)
    while(len(frontier) > 0):
        current = frontier.pop()
        # Calculating the current's neighbours
        neighbours = calculateNeighbours(current, t_size)
        for nx,ny in neighbours:
            if grid[nx,ny] == -1:
                # If the location is not visited, add it to the frontier
                frontier.append((nx,ny))
                # Mark it blocked or unblocked randomly
                grid[nx,ny] = 1 if random.random() > 0.7 else 0
    return grid

In [15]:
def create_adj_matrix(grid):
    # Convert grid to adjacency matrix
    adj_matrix = ntx.generators.lattice.grid_2d_graph(grid.shape[0],grid.shape[1])
    for i in range(len(grid)):
        for j in range(len(grid)):
            neighbours = calculateNeighbours((i,j),len(grid))
            for nx,ny in neighbours:
                if grid[nx,ny] == 1 and adj_matrix.has_edge((i,j),(nx,ny)):
                    adj_matrix.remove_edge((i,j),(nx,ny))
    return adj_matrix
#adjacency_matrix = create_adj_matrix(grid)
#print(adjacency_matrix.edges())

[((6, 9), (6, 8)), ((6, 9), (7, 9)), ((9, 8), (8, 8)), ((9, 8), (9, 7)), ((3, 7), (2, 7)), ((3, 7), (4, 7)), ((3, 7), (3, 6)), ((2, 5), (1, 5)), ((2, 5), (2, 6)), ((2, 5), (2, 4)), ((2, 5), (3, 5)), ((8, 5), (9, 5)), ((8, 5), (8, 4)), ((5, 8), (5, 7)), ((5, 8), (6, 8)), ((6, 7), (5, 7)), ((6, 7), (6, 8)), ((5, 5), (4, 5)), ((5, 5), (5, 6)), ((5, 5), (5, 4)), ((5, 5), (6, 5)), ((0, 4), (0, 3)), ((3, 5), (4, 5)), ((3, 5), (3, 4)), ((3, 5), (3, 6)), ((1, 1), (0, 1)), ((1, 1), (1, 0)), ((1, 1), (2, 1)), ((3, 2), (3, 3)), ((3, 2), (2, 2)), ((2, 6), (2, 7)), ((2, 6), (3, 6)), ((8, 2), (8, 3)), ((8, 2), (7, 2)), ((4, 5), (4, 6)), ((4, 5), (4, 4)), ((9, 3), (8, 3)), ((9, 3), (9, 4)), ((2, 3), (2, 4)), ((2, 3), (3, 3)), ((2, 3), (2, 2)), ((1, 9), (2, 9)), ((9, 6), (9, 7)), ((9, 6), (9, 5)), ((5, 3), (5, 4)), ((5, 3), (5, 2)), ((5, 3), (4, 3)), ((0, 1), (0, 0)), ((7, 0), (7, 1)), ((6, 8), (7, 8)), ((1, 7), (2, 7)), ((7, 8), (8, 8)), ((7, 8), (7, 9)), ((2, 4), (3, 4)), ((8, 4), (7, 4)), ((8, 4), 

In [2]:
def manhattan_distance(pos1,pos2):
    # Let pos1 and pos2 be i,j pairs of the coordinates
    return abs(pos2[1]-pos1[1])+abs(pos2[0]-pos1[0])

#manhattan_distance((5,5),(2,3))

In [8]:
# TEST_WORLDS = 5
TEST_WORLD_SIZE = 10
OUTPUT_BASE_PATH = "Outputs/"
grid = generateGrid(TEST_WORLD_SIZE)
today = date.today()

print(grid)
colormap = ListedColormap(["white","black"])
plt.xticks([])
plt.yticks([])
plt.imshow(X = grid, cmap = colormap)
plt.savefig(OUTPUT_BASE_PATH + today.strftime("%d-%m-%Y") + "-plain_grid" + ".svg", bbox_inches="tight")

[[0 0 1 0 0 1 1 1 0 1]
 [0 0 1 1 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 1 0]
 [1 1 0 0 0 0 0 0 1 0]
 [1 1 1 0 0 0 0 0 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 0 1 0 0 0]
 [0 0 0 1 0 1 1 1 0 0]
 [1 1 0 0 0 0 1 1 0 1]
 [0 1 1 0 0 0 0 0 0 1]]


FileNotFoundError: [Errno 2] No such file or directory: 'Outputs/27-09-2022-plain_grid.svg'

AttributeError: module 'matplotlib.colors' has no attribute 'to_rgba'